image: golang

before_script:
  - go get -u all

build:
  script:
    - mkdir dist
    - go build -o dist/docker-machine-driver-lxd-Linux-x86_64 cmd/main.go
  artifacts:
    name: binary
    paths:
      - dist

test:
  script:
    - go get github.com/jstemmer/go-junit-report
    - go test -v ./... | go-junit-report > junit.xml
  artifacts:
    paths:
      - junit.xml
    expose_as: unit test
    reports:
      junit: junit.xml
    when: always
