image: golang

variables:
  GOPATH: $CI_PROJECT_DIR/go

before_script:
  - PATH=$PATH:$GOPATH
  - go get -u all

build:
  script:
    - mkdir dist
    - go build -o dist/docker-machine-driver-lxd-Linux-x86_64 cmd/main.go
  artifacts:
    name: binary
    paths:
      - dist

test:
  script:
    - go test -v ./... | go-junit-report > junit.xml
  artifacts:
    reports:
      junit: junit.xml
